// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /cmsrm/pc18/pandolf/CMSSW_2_2_6/src/JetMETCorrections/JetAnalyzer/test/./TreeAnalyzer_finalizer.C;

#endif
