/********************************************************************
* /cmsrm/pc18/pandolf/CMSSW_2_2_6/src/JetMETCorrections/JetAnalyzer/test/./fileU0sZpJ.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /cmsrm/pc18/pandolf/CMSSW_2_2_6/src/JetMETCorrections/JetAnalyzer/test/./fileU0sZpJ.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablefileU0sZpJ();
extern void G__cpp_setup_inheritancefileU0sZpJ();
extern void G__cpp_setup_typetablefileU0sZpJ();
extern void G__cpp_setup_memvarfileU0sZpJ();
extern void G__cpp_setup_globalfileU0sZpJ();
extern void G__cpp_setup_memfuncfileU0sZpJ();
extern void G__cpp_setup_funcfileU0sZpJ();
extern void G__set_cpp_environmentfileU0sZpJ();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/cmsrm/pc18/pandolf/CMSSW_2_2_6/src/JetMETCorrections/JetAnalyzer/test/./TreeAnalyzer_finalizer.C"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__fileU0sZpJLN_TF1;
extern G__linked_taginfo G__fileU0sZpJLN_TH1D;
extern G__linked_taginfo G__fileU0sZpJLN_TH1F;
extern G__linked_taginfo G__fileU0sZpJLN_TH2D;
extern G__linked_taginfo G__fileU0sZpJLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__fileU0sZpJLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__fileU0sZpJLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__fileU0sZpJLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__fileU0sZpJLN_TFile;
extern G__linked_taginfo G__fileU0sZpJLN_TTree;
extern G__linked_taginfo G__fileU0sZpJLN_string;

/* STUB derived class for protected member access */
